
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
#tts:
#  - platform: google_translate
logger:
  default: warning
  logs:
    homeassistant.components.websocket_api.http.connection: warning
    custom_components.http_switch: debug
    homeassistant.components.hdmi_cec.switch: debug
    homeassistant.components.hdmi_cec.media_player: debug
    homeassistant.components.hdmi_cec: debug
    homeassistant.components: debug
    pycec: debug
    pycec.cec: debug

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
switch:
  - platform: mpd_outputs
    host: raspberrypi
  - platform: http_switch
    host: raspberrypi
    resources:
      projector:
        turn_on: unfold
        turn_off: fold
media_player:
  - platform: mpd
    name: Radio
    host: raspberrypi
hdmi_cec:
  types:
    hdmi_cec.hdmi_5: media_player 
  devices:
    0: TV
    5: Receiver
    8: BD-Theater
