
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
#tts:
#  - platform: google_translate
logger:
  default: info
  logs:
    custom_components.http_switch: debug
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
switch:
  - platform: mpd_outputs
    host: raspberrypi.home
  - platform: http_switch
    host: raspberrypi.home
    resources:
      projector:
        turn_on: unfold
        turn_off: fold
media_player:
  - platform: mpd
    name: Radio
    host: raspberrypi.home
